/*
USE master
DROP DATABASE RWAProject
*/

CREATE DATABASE RWAProject
GO
USE RWAProject
GO

CREATE TABLE City
(
	ID INT PRIMARY KEY IDENTITY NOT NULL,
	Name NVARCHAR(100) NOT NULL
)

INSERT INTO City VALUES
('Zagreb'),
('Varaždin'),
('Split'),
('Rijeka'),
('Pula'),
('Osijek'),
('Dubrovnik')

CREATE TABLE Role
(
	ID INT PRIMARY KEY IDENTITY NOT NULL,
	Name NVARCHAR(50) NOT NULL
)

INSERT INTO Role VALUES
('User'),
('Administrator')

CREATE TABLE Person
(
	ID INT PRIMARY KEY IDENTITY NOT NULL,
	Name NVARCHAR(100) NOT NULL,
	Surname NVARCHAR(100) NOT NULL,
	Telephone NVARCHAR(100) NOT NULL,
	Password NVARCHAR(100) NOT NULL,
	RoleID INT NOT NULL,
	CityID INT NOT NULL,

	FOREIGN KEY(RoleID) REFERENCES Role(ID),
	FOREIGN KEY(CityID) REFERENCES City(ID)
)

CREATE TABLE PersonEmail
(
	ID INT PRIMARY KEY IDENTITY NOT NULL,
	Email NVARCHAR(100) NOT NULL UNIQUE,
	PersonID INT NOT NULL,

	FOREIGN KEY(PersonID) REFERENCES Person(ID)
)